/-

-- Taken from https://github.com/pfaffelh/leancourse

-- Todo: change so that this file gets auto-generated by a references.bib file
-- Todo: book entry missing in verso

Bibliography database for the course notes.

This module plays the role of a `.bib` file: it defines the citable
references as values.  Cite them inline with the `{citet ...}[]`,
`{citep ...}[]`, or `{citehere ...}[]` roles, and list them in the
Bibliography appendix with `{citehere ...}[]`.

Only the entry types `Article`, `InProceedings`, `Thesis`, and
`ArXiv` are provided by Verso, so books and online resources are kept
as ordinary links in the text rather than as formal entries here.
-/
import VersoManual

open Verso Verso.Genre Manual

namespace DispersiveEquations.Refs

/--
A `@misc`-style entry (book, lecture notes, online resource).

Verso's `Citable` has no `Book`/`Misc`/`Online` constructor, so we
model such sources as an `InProceedings`: the `howpublished` text
(publisher, "Lecture notes", a website, ...) goes in the `booktitle`
field and is rendered after the word "In".
-/
def misc (title : Doc.Inline Manual)
    (authors : Array (Doc.Inline Manual)) (year : Int)
    (howpublished : Doc.Inline Manual)
    (url : Option String := none) : InProceedings where
  title := title
  authors := authors
  year := year
  booktitle := howpublished
  url := url

def Hormander1 : InProceedings := misc
  (title := inlines!"The analysis of linear partial differential operators. I")
  (authors := #[inlines!"Lars Hörmander"])
  (year := 2003)
  (howpublished := inlines!"Classics in Mathematics, Springer")

def Tao2006 : InProceedings := misc
  (title := inlines!"Nonlinear dispersive equations")
  (authors := #[inlines!"Terence Tao"])
  (year := 2006)
  (howpublished := inlines!"CBMS Regional Conference Series in Mathematics 106")
